name: test
on: [
  push,
  pull_request
]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.6'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
